### ISSUE TITLE
Crash at startup with 0.1.2 (1.20.1)

### ISSUE THREAD

**Issue by dooshiifox** [DAQEM/Questlines#6]
[Log file](https://mclo.gs/ltlYBv6)

Reproducible with a clean installation of Fabric 0.15.11 on Minecraft 1.20.1 and just this mod (and its dependencies)

**Comment by abrossimow** [comment]
Still present it seems. Tried it with a clean install of Fabric 1.20.1 - 0.18.4. 

```
Caused by: java.lang.NoSuchMethodError: 'com.daqem.arc.api.action.holder.type.ActionHolderType com.daqem.arc.api.action.holder.type.ActionHolderType.register(net.minecraft.class_2960)'
at knot//com.daqem.questlines.integration.arc.action.holder.QuestlinesActionHolderType.<clinit>(QuestlinesActionHolderType.java:10)
at knot//com.daqem.questlines.Questlines.init(Questlines.java:38)
at knot//com.daqem.questlines.fabric.QuestlinesFabric.onInitialize(QuestlinesFabric.java:26)
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:405)
```
